variables:
  REGISTRY: docker.oxygene.sk

build:main:
  stage: build
  script:
    - docker build --no-cache=true -t $REGISTRY/acoustid/chromaprint-build/main:latest main
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker push $REGISTRY/acoustid/chromaprint-build/main:latest
  tags:
    - docker-host
